name: X-JSP-POST

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          PYTHONIOENCODING: utf-8
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python app.py

      - name: Save state
        run: |
          git config user.name "github-bot"
          git config user.email "bot@github.com"
          git add parameters/dailyjsp/last_run.txt
          git commit -m "Increment counter"
          git push
